#pragma once

#include "GetDeviceCapabilitiesRequestDto.hpp"
#include "GetDeviceStateRequestDto.hpp"
#include "ListDevicesRequestDto.hpp"
#include "SetDeviceParameterRequestDto.hpp"
#include "StartConnectRequestDto.hpp"
#include "StartDisconnectRequestDto.hpp"
#include "StartStreamRequestDto.hpp"
#include "StopStreamRequestDto.hpp"
#include "SubscribeTelemetryRequestDto.hpp"
#include "UnsubscribeTelemetryRequestDto.hpp"
#include "WsRequestDtoMapper.hpp"
#include "WsRequestDtoVariant.hpp"
#include "WsRequestContextDto.hpp"
